name: validate playercount
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "<MaxPlayers>16</MaxPlayers>"
          replace: "<MaxPlayers>32</MaxPlayers>"
          include: "**.sbc"
          regex: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        
name: validate playercount
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "<MaxPlayers>16</MaxPlayers>"
          replace: "<MaxPlayers>32</MaxPlayers>"
          include: "**.sbc"
          regex: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4        